# Generated by Django 6.1.1 on 2026-10-06 07:13

import accounts.managers
from django.db import migrations, models


def validate_legacy_accounts_and_backfill_display_names(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    database = schema_editor.connection.alias
    users = list(User.objects.using(database).all())
    seen_emails = set()

    for user in users:
        email = (user.email or '').strip()
        if not email:
            raise RuntimeError(
                'Cannot migrate accounts with a blank email. Add a valid, unique email '
                'to every existing account, or reset this disposable development database.'
            )
        if email in seen_emails:
            raise RuntimeError(
                'Cannot migrate accounts with duplicate email addresses. Resolve duplicate '
                'emails first, or reset this disposable development database.'
            )
        seen_emails.add(email)

    for user in users:
        name_parts = [
            part.strip()
            for part in (user.first_name, user.last_name)
            if part and part.strip()
        ]
        display_name = (
            ' '.join(name_parts)
            or (user.username or '').strip()
            or user.email.split('@', 1)[0]
        )
        User.objects.using(database).filter(pk=user.pk).update(
            email=user.email.strip(),
            display_name=display_name,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.RunPython(validate_legacy_accounts_and_backfill_display_names),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=None),
    ]
